// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// The sidebar is autogenerated from the content tree on purpose. Most of this site is emitted by
// `charly docs generate` (the out-of-process plugin candy/plugin-docs), so a hand-maintained
// sidebar would need editing every time a candy, box, plugin or skill is added — exactly the
// drift the generated half exists to avoid. Adding a plugin to the marketplace manifest is
// enough to make its recipe cards appear here.
export default defineConfig({
  site: 'https://opencharly.ai',
  integrations: [
    starlight({
      title: 'OpenCharly',
      description:
        'The fully stocked gourmet kitchen for you and your agents — compose, build, deploy and evaluate boxes from a library of configurable candies.',
      social: [
        { icon: 'github', label: 'GitHub', href: 'https://github.com/opencharly/charly' },
      ],
      editLink: {
        baseUrl: 'https://github.com/opencharly/docs/edit/main/',
      },
      // Starlight >=0.39 requires an autogenerated group to be a `label` plus an `items` array
      // containing the autogenerate config — the older `{ label, autogenerate }` shape is gone.
      sidebar: [
        { label: 'Start here', items: [{ autogenerate: { directory: 'start' } }] },
        { label: 'Concepts', items: [{ autogenerate: { directory: 'concepts' } }] },
        { label: 'Guides', items: [{ autogenerate: { directory: 'guides' } }] },
        {
          label: 'Reference',
          items: [
            { label: 'Provider index', link: '/reference/providers/' },
            { label: 'CLI', collapsed: true, items: [{ autogenerate: { directory: 'reference/cli' } }] },
            { label: 'Candies', collapsed: true, items: [{ autogenerate: { directory: 'reference/candy' } }] },
            { label: 'Boxes', collapsed: true, items: [{ autogenerate: { directory: 'reference/box' } }] },
            { label: 'Plugins', collapsed: true, items: [{ autogenerate: { directory: 'reference/plugin' } }] },
          ],
        },
        { label: 'Recipe cards', collapsed: true, items: [{ autogenerate: { directory: 'recipes' } }] },
        { label: 'The Vision', link: '/vision/' },
        { label: 'What it is reacting to', link: '/grievances/' },
      ],
    }),
  ],
});
